tools:
    external_code_coverage: true

checks:
    php: true

filter:
    paths:
        - ./src/*

build:
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
