language: php

jobs:
    include:
        -
            php: "7.1"
        -
            php: "7.2"
            env: lint=1 coverage=1
        -
            php: "7.3"
        -
            php: "7.3"
            env: deps=low

cache:
    directories:
        - $HOME/.composer/cache

before_script:
    - if [[ $coverage != '1' ]]; then
          phpenv config-rm xdebug.ini || echo "xdebug not available";
      fi

install:
    - if [[ $deps = 'low' ]]; then
          composer update --prefer-dist --no-progress --no-suggest --prefer-stable --prefer-lowest --ansi;
      else
          composer update --prefer-dist --no-progress --no-suggest --ansi;
      fi
    - if [[ $lint = '1' ]]; then
          composer require friendsofphp/php-cs-fixer --prefer-dist --no-progress --no-suggest --ansi;
      fi

script:
    - if [[ $coverage = '1' ]]; then
          vendor/bin/phpunit --dump-xdebug-filter xdebug_filter.php;
          vendor/bin/phpunit --coverage-clover=coverage.clover --prepend=xdebug_filter.php;
          wget https://scrutinizer-ci.com/ocular.phar;
          php ocular.phar code-coverage:upload --format=php-clover --revision=$TRAVIS_PULL_REQUEST_SHA coverage.clover;
      else
          vendor/bin/phpunit --no-coverage;
      fi
    - if [[ $lint = '1' ]]; then
          vendor/bin/php-cs-fixer fix --dry-run --diff --no-ansi;
      fi
    - if [[ $lint = '1' ]]; then
          vendor/bin/phpstan analyse -c quality-analysis/phpstan/phpstan.neon;
      fi
